= Testen op de Proefomgeving

Heb je jouw client applicatie gerealiseerd met behulp van de xref:lokaal-testen.adoc[BRP API mock], en ben je toe aan de acceptatietest op de omgeving van RvIG?  
Dan kun je de netwerkverbinding, de toegangsbeveiliging en de communicatie met de API testen in de Proefomgeving. Iedere afnemer van RvIG / gemeente mag maximaal één aansluiting op BRP API proefomgeving realiseren. Voor de aansluiting op de proefomgeving is nog geen convenant nodig.

== Voorwaarden

* aansluiten mag alleen met met een API Gateway
* aansluiting op link:https://www.logius.nl/domeinen/infrastructuur/diginetwerk/aansluiten[DigiNetwerk]
* TLS met PKIO certificaat met OIN: het PKIO certificaat met OIN voor de proefomgeving kun je ook gebruiken in de productieomgeving. Gebruikt jouw API Gateway al een PKIO certificaat voor een ander product van RvIG? Dan kun je dat certificaat opnieuw gebruiken. Heb je een aparte API Gateway voor test en productie? Dan zijn aparte certificaten vereist. Dit komt omdat we geen clientcertificaten installeren, Bij iedere transactie wordt het certificaat en het OIN gecontroleerd op geldigheid.

Voor je de API kunt gebruiken moet je een token vragen. Voor het aanvragen heb je nodig:

* Client-id: deze ontvang je van RvIG
* Client-secret: deze ontvang je van RvIG
* afnemersindicatie: dit is het nummer dat hoort bij je autorisatiebesluit. Dit kun je link:https://publicaties.rvig.nl/zoekpagina-tabel-35-autorisatietabel[hier opzoeken].
* OIN: zit in het PKI overheidscertificaat dat je gebruikt bij het aansluiten.

== Stap 1: Stuur aanvraag client credentials voor de proefomgeving naar info@rvig.nl

* Vermeld daarbij het juiste OIN in het gebruikte PKIO certificaat en geef jouw contactpersoon op met naam, e-mail adres en mobiel nummer.
* Jouw contactpersoon ontvangt binnen 2 weken een client ID en een client secret. Deze mogen alleen bekend zijn bij jouw API Gateway.

== Stap 2: Configureer jouw Gateway
Belangrijke informatie voor de configuratie van jouw Gateway:

* sluit aan via DigiNetwerk
* URL voor aanvraag van het token: https://auth.npr.idm.diginetwerk.net/nidp/oauth/nam/token
* URL BRP API Personen: https://apigw.npr.idm.diginetwerk.net/lap/api/brp/personen
* URL BRP API Bewoning: https://apigw.npr.idm.diginetwerk.net/lap/api/bewoning/bewoningen
* URL BRP API Verblijfplaatshistorie: https://apigw.npr.idm.diginetwerk.net/lap/api/brp/verblijfplaatshistorie

== Stap 3: Haal het Oauth token op
Stuur dit request om op de proefomgeving een token aan te vragen, en vervang alles wat tussen dubbele accolades staat met de inloggegevens die je hebt:

[source,shell]
----
curl --location -–request POST 'https://auth.npr.idm.diginetwerk.net/nidp/oauth/nam/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'client_id={{client-id}}' \
--data-urlencode 'client_secret={{client-secret}}' \
--data-urlencode 'scope={{ afnemersindicatie }}-{{OIN}}' \
--data-urlencode 'resourceServer=ResourceServer01'
----

Je krijgt dan als antwoord een application/json bericht dat er zo uitziet:

[source,json]
----
{
  "access_token": "{{access token}}",
  "token_type": "bearer",
  "expires_in": {{geldigheidsduur}},
  "scope": "{{scope}}"
}
----

Het token in "access_token" stuur je mee met elk request aan de API door deze in te vullen in de request header "Authorization", voorafgegaan door "Bearer ". Let op dat er 1 spatie staat tussen "Bearer" en het token en er geen spatie of ander teken staat na het token!
De token is beperkt geldig en kun je gedurende de geldigheidsperiode voor meerdere API requests gebruiken. In "expires_in" staat hoe lang (in seconden) het token geldig is.

== Stap 4: Stuur een request
Stuur dit request met correct voorbeeld-request-body naar de API op de proefomgeving:

[source,shell]
----
curl --location -–request POST 'https://apigw.npr.idm.diginetwerk.net/lap/api/brp/personen' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer {{access_token}} \
--data '{
  "fields": ["naam.volledigeNaam", "leeftijd", "geslacht", "adressering"],
  "type": "RaadpleegMetBurgerservicenummer",
  "burgerservicenummer": ["999993483"]
}'
----

== Stap 5: Test jouw client applicatie
Test jouw applicatie met link:https://www.rvig.nl/testsetpersoonslijstenproefomgevingBRPV[deze testset] . Geslaagd? Dan kun je een aansluiting op de productieomgeving aanvragen.

== Aansluiten productie-omgeving

== Voorwaarden

* een door jouw gemandateerde ondertekend convenant
* een link:https://publicaties.rvig.nl/zoeken[BRP autorisatiebesluit] en een aanvullend autorisatiebesluit voor informatieproducten (niet voor gemeenten)
* aansluiten mag uitsluitend met een API Gateway
* aansluiting op link:https://www.logius.nl/domeinen/infrastructuur/diginetwerk/aansluiten[DigiNetwerk]
* TLS met PKIO certificaat/certificaten met OIN: het PKIO certificaat met OIN voor de proefomgeving kun je ook gebruiken in de productieomgeving. Heb je een aparte API Gateway voor test en productie? Dan zijn aparte certificaten vereist. Dit komt omdat we geen clientcertificaten installeren, Bij iedere transactie wordt het certificaat en het OIN gecontroleerd op geldigheid.

== Stap 1: Vraag de aansluiting op de productieomgeving aan via info@rvig.nl. Je ontvangt dan een concept Convenant.

* Vermeld daarbij het juiste OIN in het gebruikte PKIO certificaat en geef jouw contactpersoon op met naam, e-mail adres en mobiel nummer.
* Het convenant moet door burgemeester, gemeente secretaris of gemandateerde ondertekend worden en naar info@rvig.nl gezonden. Stuur een mandaat besluit mee indien getekend door een gemandateerde. Na controle door RvIG kunnen de client credentials worden uitgegeven.
* Jouw contactpersoon ontvangt binnen 2 weken een client ID en een client secret. Deze mogen alleen bekend zijn bij jouw API Gateway.

== Stap 2: Configureer jouw Gateway
Belangrijke informatie voor de configuratie van jouw Gateway:

* sluit aan via DigiNetwerk
* URL voor aanvraag van het token: https://auth.idm.diginetwerk.net/nidp/oauth/nam/token
* URL BRP API Personen: https://apigw.idm.diginetwerk.net/api/brp/personen
* URL BRP API Bewoning: https://apigw.idm.diginetwerk.net/api/brp/bewoning/bewoningen
* URL BRP API Verblijfplaatshistorie: https://apigw.idm.diginetwerk.net/api/brp/verblijfplaatshistorie
