= Probeer en test de API

Je kan de API uitproberen en gebruiken bij het ontwikkelen en testen op onze probeeromgeving. De API op deze omgeving is bereikbaar over internet en vereist geen Diginetwerk en je hebt geen PKI-overheid certificaat nodig. 
Je kan de functionaliteit van de API uitproberen, maar de aansluiting en autorisaties kunnen anders zijn dan in productie. De probeeromgeving is dus bedoeld als eerste stap voor het ontwikkelen.

== Toegang vragen

De API op de probeeromgeving vereist - net als in productie - dat een OAuth token wordt meegestuurd. Hiervoor heb je client credentials nodig. Vraag deze aan door een e-mail te sturen naar info@rvig.nl. Geef in die e-mail aan voor welke organisatie je credentials wilt en geef je contactgegevens op. Die gebruiken we om je te informeren over belangrijke wijzigingen. gepland onderhoud, enz.

== De API uitproberen met Postman

We hebben een Postman project klaargezet waarmee je snel aan de slag kunt met de Personen API. 

link:https://elements.getpostman.com/redirect?entityId=6707821-5940172f-a50a-4a66-b61b-b3bb63fb0287&entityType=collection&workspaceId=fbc0d981-545f-4f19-9ef3-f126d4b4d522[image:https://run.pstmn.io/button.svg[Run in Postman, width=128, height=32]]

Om dit te laten werken op de probeeromgeving moet je in Postman de volgende waarden invullen bij Variables:

* tokerserviceUrl: https://probeerbrpapi.rvig.nl/realms/brp-api/protocol/openid-connect/token
* baseUrl: https://probeerbrpapi.rvig.nl/api/brp
* client_id: *dit ontvang je van ons als je toegang hebt aangevraagd*
* client_secret: *dit ontvang je van ons als je toegang hebt aangevraagd*
* scope: *dit ontvang je van ons als je toegang hebt aangevraagd*
* resourceServer: ResourceServer02

== Hoe het werkt

Om op de probeeromgeving een token aan te vragen stuur je een request zoals deze:
```
curl --location -–request POST 'https://probeerbrpapi.rvig.nl/realms/brp-api/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'client_id={{client-id die je van ons ontvangt als je toegang hebt aangevraagd}}' \
--data-urlencode 'client_secret={{client-secret die je van ons ontvangt als je toegang hebt aangevraagd}}' \
--data-urlencode 'scope={{scope die je van ons ontvangt als je toegang hebt aangevraagd}}' \
--data-urlencode 'resourceServer=ResourceServer02'
```

Hier moet je alles wat tussen dubbele accolades staat vervangen door de inloggegevens die je hebt ontvangen.
 
Je krijgt dan als antwoord een application/json bericht dat er zo uitziet (maar dan met een echte access token in plaats van allemaal X-en):
```
{
  "access_token": "XXXXXXX-XXX.XXX-XXX-XXXX-XXXX-XXXX.XXXXXXXX-XXXXXXXX-XXXXXXX-XXXXXX",
  "token_type": "bearer",
  "expires_in": 3599,
  "scope": "{{scope}}"
}
```

Om op de probeeromgeving een request te sturen naar de API, stuur je een request zoals deze:
```
curl --location -–request POST 'https://probeerbrpapi.rvig.nl/api/brp/personen' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer {{Oauth token}} \
--data '{
  "fields": ["naam", "geboorte.datum", "geslacht", "adressering" ],
  "type": "RaadpleegMetBurgerservicenummer",
  "burgerservicenummer": ["999993483"]
}'
```

Hierin vul je de Oauth token (op de plek waar {{Oauth token}} staat) met de waarde zoals ontvangen van de token server in veld access_token.

== Testpersonen

De testdata op de probeeromgeving is in principe gelijk aan de https://www.rvig.nl/testsetpersoonslijstenproefomgevingBRPV[testdata op de proefomgeving van de RvIG]. 
De testdata op de probeeromgeving wordt niet bijgehouden, de testdata op de proefomgeving van RvIG wijzigt wel regelmatig. Om die reden kan (zal) de testdata voor sommige personen op de probeeromgeving afwijken van de testset van de proefomgeving.

Enkele voorbeelden waarmee je de API kunt uitproberen:

* persoon met immigratie, vreemde nationaliteit en verblijfstitel: burgerservicenummer "999995017"
* overleden persoon: burgerservicenummer "999992077"
* persoon in RNI (geëmigreerd naar het buitenland): burgerservicenummer "999993483"
* persoon gehuwd en met gezag over meerdere kinderen: burgerservicenummer "999970513"
* persoon met geboortedatum in onderzoek: burgerservicenummer "999994086"
* adres met meerdere bewoners: postcode "2548AE" en huisnummer 1485
