= De gemeente als verstrekker van persoonsinformatie

De gemeente mag de {apiname} gebruiken om de BRP-V te **raadplegen**, met het doel informatie over personen aan binnengemeentelijke afnemers te **verstrekken**. Dit geldt voor het verstrekken van gegevens over eigen inwoners en buitengemeentelijke personen. De rol van gemeenten als verstrekker brengt verplichtingen met zich mee. De gemeente moet:

. rechtmatig verstrekken door uitsluitend binnengemeentelijke afnemers te autoriseren op basis van een wettelijke grondslag
. zorgen voor veilig gebruik van de persoonsgegevens door:
+
  * uitsluitend geautoriseerde gebruikers van taakapplicaties toegang te geven.
  * gebruikers uitsluitend toegang te geven tot gegevens waarvoor zij zijn geautoriseerd.
. transparant zijn over de verwerking van persoonsgegevens
+
  * door alle bevragingen te protocolleren/loggen
  * door een burger inzicht te geven welke persoonsgegevens verwerkt zijn voor welke doeleinden, als die burger daar om vraagt.
. toezicht houden op de rechtmatige verwerking van persoonsgegevens en onrechtmatig gebruik opsporen.

== Centrale regie op beveiliging
Om veilig te kunnen werken met de {apiname} moet je drie zaken regelen:

. Toegangsbeveiliging, autorisatie en filtering
. Logging- en protocollering voor controle achteraf en het voorkomen van misbruik
. Beheer van identiteiten, rollen en rechten

Dit wordt van oudsher geheel of gedeeltelijk geregeld in de taakapplicaties of het gegevensmagazijn. In de transitie naar het werken met de {apiname} en SaaSapplicaties is het belangrijk dat deze functies centraal in de gemeente worden belegd, en worden uitgevoerd door onafhankelijke, door de gemeente gecontroleerde voorzieningen. Zo houd je als gemeente de regie!

== Toegangsbeveiliging, autorisatie en filtering
Gemeenten bieden een divers palet aan producten en diensten die vaak andere gegevens en informatieproducten nodig hebben. Daarvoor zetten zij taakapplicaties in, die worden gebruikt door medewerkers met verschillende rollen en rechten. Gemeenten moeten hiervoor zelf de toegangsbeveiliging en autorisatie organiseren. Wat is daarvoor nodig?

=== 1. Identity Provider (IP)
Voor het authenticeren van de eindgebruiker waarin de claims voor het gebruik van de {apiname} van alle gebruikers van jouw gemeente centraal zijn vastgelegd. Nadat de Identity Provider heeft vastgesteld wie de ingelogde gebruiker is en welke applicatie de {apiname} namens de gebruiker gaat bevragen, kunnen tokens (al dan niet met gebruikersclaims) aan client (SaaS) applicaties worden verstrekt. Hiermee kan de client (SaaS)applicatie namens de gebruiker de {apiname} bevragen.

=== 2. API Gateway
Voor de (toegangs)beveiliging van de {apiname} en alle andere API’s. Een API Gateway is vaak onderdeel van een product voor API Management. Een API Gateway bevat ondersteuning voor het design, publiceren, documenteren, beveiligen en analyseren van API’s. Een API Gateway is een must have voor iedere gemeente die gevoelige API’s aan afnemers aanbiedt.

=== 3. Proxy
Voor autorisatie op detailniveau. Met welke rol of taak mag een medewerker of applicatie welke set gegevens opvragen? Hiervoor maak je gebruik van de xref:personen-response-filteren.adoc[filtermogelijkheden] die de {apiname} biedt. Dit kun je regelen in jouw API Gateway, zoals in link:https://github.com/Amsterdam/haal-centraal-proxy[dit voorbeeld van de gemeente Amsterdam].

== Logging- en protocollering
Protocollering is een verplichte vorm van logging om een burger inzicht te geven welke persoonsgegevens door wie en met welk doel zijn opgevraagd. Een gemeente moet alle bevragingen met de {apiname} protocolleren en 20 jaar bewaren. Dat gebeurt nu meestal in diverse procesapplicaties. Het is beter om een centrale logging- of protocolleringsvoorziening in te richten, waarin wordt vastgelegd:

* over wie gegevens zijn verstrekt;
* datum en tijd van de verstrekking;
* welke gegevens zijn verstrekt;
* aan welk binnengemeentelijk orgaan de verstrekking plaatsvond;
* het taaksysteem en/of de ambtenaar met een bepaalde taakautorisatie die de verstrekking heeft ontvangen. 

Dit kan bijvoorbeeld door ieder request voor zowel zoeken als raadplegen onweerlegbaar vast te leggen met:

* een timestamp;
* het token dat de identiteit, het orgaan en claims van de eindgebruiker en/of het bevragende systeem bevat;
* de BSN's van de personen die in het antwoord voorkomen.

Er zijn twee dingen waar je op moet letten:

* het kan voorkomen dat jouw binnengemeentelijke afnemer het BSN niet vraagt. Zorg dus dat het BSN in het request van jouw API Gateway aan RvIG xref:personen-response-filteren.adoc[altijd gevraagd] wordt! Dit kun je regelen in jouw API Gateway als intermediate endpoint.
* als je alleen het taaksyssteem en niet de identiteit van de ambtenaar centraal protocolleert, kun je weliswaar alle AVG inzageverzoeken met de centrale protocolleringsgegevens beantwoorden, maar geen onderzoek doen naar de rechtmatigheid van bevragingen. Zorg in dat geval altijd voor logging in het taaksysteem waaruit blijkt welke ambtenaar de bevraging heeft gedaan. Door de API Gateway ook de indentiteit van de ambtenaar centraal te laten loggen is opsporing van misbruik gemakkelijker en hoef je straks niet meer te protocolleren in de afnemende taakapplicatie.

Eventueel kun je de logging verrijken met informatie over wettelijke taken en doelbinding uit je verwerkingsregister om burgerverzoeken in het kader van de AVG zo informatief mogelijk te maken.

Voor het centraal verzamelen, opslaan en analyseren van de logging, en het maken van protocolleringsoverzichten, kun je bijvoorbeeld gebruik maken van een product als de ELK Stack (Elastic search, Logstash en Kibana), Splunk, LogRhythm, etc.

== Identity Provider (IP)
Een Identity provider heb je nodig voor het authenticeren van de eindgebruiker. In de identity provider kun je de claims/autorisaties voor het gebruik van de {apiname} van alle gebruikers van jouw gemeente centraal vastleggen.

Nadat de Identity provider heeft vastgesteld wie de ingelogde gebruiker is en welke applicatie de {apiname} namens de gebruiker wil bevragen, kunnen tokens (al dan niet met gebruikersclaims) aan client applicaties worden verstrekt.

Hiermee kan de client (SaaS)applicatie namens de gebruiker de {apiname} bevragen.
