= Welkom bij de {apiname}

---

== Zoek en raadpleeg persoonsinformatie

API voor het zoeken en raadplegen van informatie uit de basisregistratie
personen (BRP). De {apiname} heeft drie functies:

1. *Personen*: voor het zoeken en raadplegen van actuele personen,
   partners, ouders en kinderen uit de BRP, inclusief de registratie
   niet-ingezeten (RNI).
2. *Bewoning*: voor het raadplegen van de historische bewoning van een
   adres. Met de API kun je de samenstelling(en) van bewoners van een
   woning raadplegen binnen een periode of op een peildatum.
3. *Verblijfplaatshistorie*: voor het opvragen van de
   verblijfplaats(en) van een persoon in een periode of op een peildatum.

De {apiname} levert naast persoonsgegevens uit de BRP ook xref:informatieproducten.adoc[informatieproducten]:

* xref:personen:informatieproducten/adressering/index.adoc[Adressering]: *aanschrijfwijze*, *aanhef*, een verwijzing naar een *persoon in de lopende tekst* van een brief, en *adresregels* die passen in een envelopvenster.
* xref:bewoning:documentatie.adoc[Bewoning]: wie er samen in een woning woonde gedurende een periode, of op een peildatum.
* xref:personen:informatieproducten/gezag.adoc[Gezag]: gezagsrelaties van alle minderjarigen en gezagshouders, ook als er geen aantekening is in het gezagsregister.
* xref:personen:informatieproducten/leeftijd.adoc[Leeftijd]: (in jaren).
* xref:personen:informatieproducten/volledige-naam.adoc[Volledige naam]: met adellijke titels en predicaten, zonder gebruik van de naam van de partner.
* xref:personen:informatieproducten/voorletters.adoc[Voorletters].

== Aan de slag

Als developer kun je direct aan de slag. Lees in de
xref:getting-started.adoc[Getting Started] hoe je zo snel mogelijk een
eerste succesvolle API call doet.

De {apiname} eerst uitproberen? Gebruik de
xref:lokaal-testen.adoc[lokaal testen gids] om je eerste API call
te doen!

== Voorwaarden

Aansluiten mag alleen met:

1. een https://publicaties.rvig.nl/zoeken[BRP autorisatiebesluit]. Controleer of jouw organisatie of klant (als je een leverancier bent) een autorisatiebesluit heeft.
2. een aanvullend autorisatiebesluit voor informatieproducten. Voor gemeenten is dit niet nodig. Download hier het https://www.rvig.nl/media/898[autorisatieaanvraagformulier].
3. een ondertekend convenant voor deelname aan het https://www.digitaleoverheid.nl/nieuws/doe-mee-met-het-experiment-informatieproducten-uit-de-brp/[Experiment Dataminimalisatie].
4. een aansluiting op https://www.logius.nl/domeinen/infrastructuur/diginetwerk/aansluiten[DigiNetwerk].
5. een API Gateway.

== Documentatie

De documentatie is alsvolgt opgebouwd:

* How-Tos: praktische gidsen die jou helpen bij het implementeren van de
{apiname} in jouw applicatie.
* Concepten: uitleg van belangrijke onderwerpen die een rol spelen bij
het gebruik van de {apiname}.
* Referenties: de specificaties van de {apiname} functies Personen,
Verblijfplaatshistorie en Bewoning.

== Planning en Roadmap

De vierde functie van de {apiname} is in ontwikkeling: de {apiname} Gebeurtenissen. Deze is na livegang voorlopig alleen beschikbaar voor gemeenten.

Er is ook een probeeromgeving beschikbaar via internet voor het uitproberen van de {apiname}. Deze is representatiever dan de mock voor het lokaal uitproberen van de {apiname}. Toegang kun je aanvragen via info@rvig.nl.

== Contact

* Storing melden? +
Neem contact op met de *RvIG servicedesk*: op werkdagen telefonisch
bereikbaar tussen 08.30 en 17.00 uur via 088-9001000. Vanuit het
buitenland bel je naar: +31 707511000. Je kunt ook een e-mail sturen
naar info@rvig.nl.
* Bug Melden?
https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/issues/new?assignees=&labels=bug&template=bug_report.md&title=[Maak
een bug issue aan]
* Verbetersuggestie doen voor de {apiname} of de documentatie op
deze portal?
https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/issues/new?assignees=&labels=enhancement&template=enhancement.md&title=[Maak
een verbeter issue aan]
* Heb je een vraag? Neem contact op met info@rvig.nl onder vermelding BRP API


== Licentie

Copyright © RvIG 2024 Licensed under the
link:{main-branch-url}/LICENCE.md[EUPL]
