openapi: 3.1.0
servers:
  - description: |
      Proef omgeving
    url: https://proefomgeving.haalcentraal.nl/haalcentraal/api/bewoning
  - description: |
      Lokaal
    url: http://localhost:5010/haalcentraal/api/bewoning
info:
  title: Haal Centraal BRP bewoning
  description: |
    API voor het raadplegen van de (historische) bewoning van een adres.
  version: 2.1.0
  contact:
    url: https://github.com/BRP-API/Haal-Centraal-BRP-bewoning
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
tags:
  - name: Bewoning
paths:
  /bewoningen:
    post:
      summary: Raadplegen van bewoningen
      description: |
        Met de API kun je raadplegen:

        **Bewoning:**
        welke personen (bewoners) een adresseerbaar object bewoonden op een opgegeven moment (peildatum) of
        welke samenstellingen van personen een adresseerbaar object bewoonden in een opgegeven periode.
      operationId: Bewoningen
      requestBody:
        content:
          'application/json; charset=utf-8':
            schema:
              $ref: '../bewoningen/@1/BewoningenQuery.yaml#/components/schemas/BewoningenQuery'
      responses:
        '200':
          description: |
            Zoekactie geslaagd
          content:
            'application/json; charset=utf-8':
              schema:
                $ref: ./@1/BewoningenQueryResponse.yaml
        '400':
          $ref: ../shared/problem-details/@1/400.yaml
      tags:
        - Bewoning
